language: bash

# Use container-based infrastructure for quicker build start-up
sudo: false

before-script:
  - "sudo apt-get install cabal-install"
  - "cabal update"
  - "cabal install shellcheck"

script:
 - shellcheck exposure_fusion.sh

matrix:
fast_finish: true
